### ISSUE TITLE
DecimalFields must define a 'max_digits'/'max_places' attribute.

### ISSUE THREAD

**Issue by cdvv7788** [mirumee/django-prices#21]
I am getting these errors when trying to migrate:

DecimalFields must define a 'decimal_places' attribute.
DecimalFields must define a 'max_digits' attribute

My code (just like front page):

```python
class Product(models.Model):
    name = models.CharField('Name')
    price = PriceField('Price', currency='BTC')
```

I am using django1.8.3.
Am i missing something? Is there any restriction for the values of those attributes?
If those attributes are required, it should be reflected on the readme.

**Comment by bogdal** [comment]
These parameters are required. Added to the README. Thanks.
