### ISSUE TITLE
Nicer rendering

### ISSUE THREAD

**Issue by mjtamlyn** [mirumee/django-prices#32]
I can't see an obvious way to get `$5` rendered instead of `$5.00` for round numbers. The equivalent of what `{{ price|floatformat:"-2" }}` would do.

**Comment by patrys** [comment]
This is interesting since in some contexts having a shorter number may look better (assuming it's common in current locale) but in others may cause confusion.

For example:

> Order *now* and get it as low as **$5**!

But:

> ```
Foo           $123.50
Bar             $5.50
Baz               $50
---------------------
Total:           $179
```

**Comment by mjtamlyn** [comment]
Agreed, I don't think it's a change you should have by default, but it's a pretty reasonable one to have a nice API/templatetag/filter/whatever for.

**Comment by patrys** [comment]
This is now possible with the new API.
