### ISSUE TITLE
Korean won is displayed "3300,000 원"

### ISSUE THREAD

**Issue by pcompassion** [mirumee/django-prices#33]
when locale is Locale('ko', territory='KR')

Currently, displayed as "원 3300000.00"

**Comment by patrys** [comment]
It looks like you're using `prices_i18n` which in turn depend on [Babel](http://babel.pocoo.org/en/latest/). Are you sure this bug is in `django-prices`?

**Comment by pcompassion** [comment]
oh..

It might be a bug of babel.

babel takes parameters (such as format) django-prices won't pass.
So It might be configurable by setting correct parameters though.

2016-02-16 20:10 GMT+09:00 Patryk Zawadzki <notifications@github.com>:

**Comment by pcompassion** [comment]
actually it is the babeldjango that doesn't accept the whole parameter
set..

2016-02-16 20:12 GMT+09:00 eugene kim <p.compassion@gmail.com>:

**Comment by patrys** [comment]
We pass the current locale to Babel's `format_currency`. For me that's what it returns:

```python
from babel.numbers import format_currency
print(format_currency(3300000, 'KRW', locale='ko_KR'))
# ₩3,300,000
```

**Comment by pcompassion** [comment]
oh..

That looks ok.

although we koreans are more accustomed to see 
`3,300,000 원`

I'm closing this is minor issue. 
(it is better to get the `3,300,000 원` but I guess It is better to talk to babel people)
